version: '3.6'

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.7
  INSTALL_NODE_VERSION: 12

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules

services:
  database:
    image: postgres:10.6
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=hacker
      - POSTGRES_PASSWORD=hacker
      - POSTGRES_DB=hacker
    volumes:
      - hackerdb:/var/lib/postgresql/data
    networks:
      - hacker

  flask-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "flask_hackernews_clone-development"
    ports:
      - "5000:5000"
      - "2992:2992"
    depends_on:
      - database
    networks:
      - hacker
    <<: *default_volumes


  flask-prod:
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: "flask_hackernews_clone-production"
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
    <<: *default_volumes

  manage:
    build:
      context: .
      target: manage
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "flask_hackernews_clone-manage"
    stdin_open: true
    tty: true
    depends_on:
      - database
    networks:
      - hacker
    <<: *default_volumes

volumes:
  node-modules:
  static-build:
  hackerdb:

networks:
  hacker:
    driver: bridge