"""add fields to User model

Revision ID: 7f7aa29c6289
Revises: 0b8a5fe7f268
Create Date: 2020-09-24 03:59:15.849309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7aa29c6289'
down_revision = '0b8a5fe7f268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about')
    # ### end Alembic commands ###
